INSERT INTO equipment (name, description, quantity, status) VALUES
('Football', 'Standard size 5 soccer ball', 10, 'available'),
('Basketball', 'Official size 7 basketball', 8, 'available'),
('Tennis Racket', 'Wilson Pro Staff, adult size', 12, 'available'),
('Tennis Balls', 'Pack of 3, yellow', 20, 'available'),
('Volleyball', 'Mikasa V200W, indoor', 6, 'available'),
('Badminton Racket', 'Yonex Nanoray, lightweight', 15, 'available'),
('Shuttlecocks', 'Feather, pack of 12', 10, 'available'),
('Hockey Stick', 'Composite, 36.5 inch', 7, 'available'),
('Table Tennis Paddle', 'Butterfly, all-round', 10, 'available'),
('Table Tennis Balls', 'Pack of 6, white', 15, 'available'),
('Cricket Bat', 'English willow, full size', 5, 'available'),
('Cricket Ball', 'Leather, red', 12, 'available'),
('Rugby Ball', 'Gilbert, size 5', 6, 'available'),
('Cones', 'Training cones, set of 20', 4, 'available'),
('Whistle', 'Metal, with lanyard', 10, 'available'),
('Stopwatch', 'Digital, waterproof', 5, 'available'),
('Netball', 'Size 5, synthetic', 8, 'available'),
('Gym Mat', '6ft x 2ft, foam', 10, 'available'),
('Jump Rope', 'Adjustable, plastic', 15, 'available'),
('First Aid Kit', 'Complete, for field use', 3, 'available'); 